app/student_admin/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired
from wtforms import BooleanField
from wtforms_alchemy import model_form_factory

from app import db
from app.services.models import *

BaseModelForm = model_form_factory(FlaskForm)


class ModelForm(BaseModelForm):
    @classmethod
    def get_session(self):
        return db.session


class AddressForm(ModelForm):
    class Meta:
        model = ClientAddress


class OrganismForm(ModelForm):
    class Meta:
        model = Organism


class ClientUploadForm(FlaskForm):
    upload = FileField('File Upload', validators=[FileRequired()])
    random_pid = BooleanField('Generate random PID', default=False)
    use_lab_number_as_client_number = BooleanField('Use lab number as client number', default=False)

app/student_admin/__init__.py
from flask import Blueprint

admin_bp = Blueprint('student_admin', __name__, url_prefix='/student-student_admin')


from . import views

app/student_admin/views.py
import random

from flask import render_template, flash, redirect, url_for, request, make_response
from flask_login import login_required, current_user

from app import db, superuser
from app.services.models import User, ClientAddress, Organism, Client, StoolTestRecord
from app.student_admin import admin_bp as admin
from app.student_admin.forms import AddressForm, OrganismForm, ClientUploadForm
import pandas as pd


@admin.route('/projects/<int:project_id>')
@superuser
@login_required
def index(project_id):
    return render_template('student_admin/index.html', project_id=project_id)


@admin.route('/projects/<int:project_id>/users')
@superuser
@login_required
def list_users(project_id):
    users = User.query.filter_by(is_approved=False)
    return render_template('student_admin/users.html', users=users, project_id=project_id)


@admin.route('/projects/<int:project_id>/users/<int:user_id>/approve')
@superuser
@login_required
def approve_user(user_id, project_id):
    u = User.query.get(user_id)
    if u:
        u.is_approved = True
        db.session.add(u)
        db.session.commit()
        flash('The user has been approved', 'success')
        return redirect(url_for('student_admin.list_users', project_id=project_id))


@admin.route('/projects/<int:project_id>/addresses/add', methods=['GET', 'POST'])
@admin.route('/projects/<int:project_id>/addresses/<int:addr_id>/edit', methods=['GET', 'POST', 'DELETE'])
@superuser
@login_required
def edit_address(addr_id=None, project_id=None):
    addresses = ClientAddress.query.filter_by(project_id=project_id)
    if addr_id:
        addr = ClientAddress.query.get(addr_id)
        form = AddressForm(obj=addr)
        if request.method == 'DELETE':
            db.session.delete(addr)
            db.session.commit()
            resp = make_response()
            return resp
    else:
        form = AddressForm()

    if form.validate_on_submit():
        if addr_id:
            form.populate_obj(addr)
            flash('The address has been updated.', 'success')
            db.session.add(addr)
        else:
            new_addr = ClientAddress(project_id=project_id)
            form.populate_obj(new_addr)
            flash('New addresss has been added.', 'success')
            db.session.add(new_addr)
        db.session.commit()
    return render_template('student_admin/address_form.html',
                           project_id=project_id,
                           form=form, addresses=addresses, addr_id=addr_id)


@admin.route('/organisms/add', methods=['GET', 'POST'])
@admin.route('/organisms/<int:org_id>/edit', methods=['GET', 'POST'])
@superuser
@login_required
def edit_organism(org_id=None):
    project_id = request.args.get('project_id')
    organisms = Organism.query.all()
    if org_id:
        org = Organism.query.get(org_id)
        form = OrganismForm(obj=org)
    else:
        form = OrganismForm()

    if form.validate_on_submit():
        if org_id:
            form.populate_obj(org)
            flash('The organism has been updated.', 'success')
            db.session.add(org)
        else:
            new_org = ClientAddress()
            form.populate_obj(new_org)
            flash('New organism has been added.', 'success')
            db.session.add(new_org)
        db.session.commit()
    return render_template('student_admin/organism_form.html',
                           project_id=project_id,
                           form=form, organisms=organisms, org_id=org_id)


@admin.route('/projects<int:project_id>/clients/upload', methods=['GET', 'POST'])
@superuser
@login_required
def upload_clients(project_id):
    form = ClientUploadForm()
    if form.validate_on_submit():
        f = form.upload.data
        df = pd.read_excel(f)
        for idx, row in df.iterrows():
            client = Client(
                firstname=row['firstname'],
                lastname=row['lastname'],
                project_id=project_id,
                updated_by=current_user,
            )
            if form.use_lab_number_as_client_number.data:
                client.client_number = row['labno']
            if form.random_pid.data:
                client.pid = 'fake' + ''.join([str(random.randint(0, 9)) for i in range(9)])
            if row.get('address'):
                address = ClientAddress.query.filter_by(name=row.get('address')).first()
                client.address = address
            db.session.add(client)
            if row.get('stool'):
                if row.get('stool') is True:
                    record = StoolTestRecord(
                        client=client,
                        method=row.get('stool_method'),
                        lab_number=row.get('labno')
                    )
                    db.session.add(record)
        db.session.commit()
    else:
        for field, errors in form.errors.items():
            flash(f'{field} : {errors}', 'danger')
    return render_template('student_admin/upload_clients.html', form=form)

app/templates/student_admin/address_form.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    {% include "messages.html" %}
    <div class="columns">
      <div class="column">
        <table class="table is-striped">
          <thead>
          <th>Address</th>
          <th></th>
          </thead>
          <tbody>
          {% for addr in addresses %}
          <tr>
            <td>{{addr.name}}</td>
            <td>
              <a href="{{url_for('student_admin.edit_address', addr_id=addr.id, project_id=project_id)}}" class="button is-light">
                <span class="icon">
                  <i class="fas fa-pencil-alt"></i>
                </span>
              </a>
              <a hx-delete="{{url_for('student_admin.edit_address', addr_id=addr.id, project_id=project_id)}}" class="button is-danger" hx-target="closest tr" hx-swap="outerHTML"
                 hx-indicator="this"
                 hx-confirm="Do you want to delete this record?"
              >
                <span class="icon"><i class="fas fa-trash-alt"></i></span>
              </a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <form method="post">
          {{form.hidden_tag()}}
          <div class="field">
            <label class="label">{{form.name.label}}</label>
            <div class="control">
              {{form.name(class="input")}}
            </div>
          </div>
          <div class="field">
            <input type="submit" {% if addr_id %} value="Save" {% else %} value="Add" {% endif %}
                   class="button is-primary">
          </div>
        </form>
        <div class="buttons is-centered">
          <a class="button is-light" href="{{url_for('student_admin.index', project_id=project_id)}}">
            Back
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/student_admin/index.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        {% include "messages.html" %}
        <div class="columns">
            <div class="column is-two-thirds is-offset-2 has-text-centered">
                <nav class="panel is-primary">
                    <p class="panel-heading">
                        Menu
                    </p>
                    <a class="panel-block is-active" href="{{url_for('student_admin.list_users', project_id=project_id)}}">
                        <span class="panel-icon">
                          <i class="fa-solid fa-chevron-right"></i>
                        </span>
                        <span class="is-size-4">
                            อนุมัติผู้ใช้ระบบ
                        </span>
                    </a>
                    <a class="panel-block is-active" href="{{url_for('student_admin.edit_address', project_id=project_id)}}">
                        <span class="panel-icon">
                          <i class="fa-solid fa-chevron-right"></i>
                        </span>
                        <span class="is-size-4">
                            เพิ่ม/แก้ไขที่อยู่
                        </span>
                    </a>
                    <a class="panel-block is-active" href="{{url_for('student_admin.edit_organism', project_id=project_id)}}">
                        <span class="panel-icon">
                          <i class="fa-solid fa-chevron-right"></i>
                        </span>
                        <span class="is-size-4">
                            เพิ่ม/แก้ไขเชื้อปรสิต
                        </span>
                    </a>
                    <a class="panel-block is-active" href="{{url_for('student_admin.upload_clients', project_id=project_id)}}">
                        <span class="panel-icon">
                          <i class="fa-solid fa-chevron-right"></i>
                        </span>
                        <span class="is-size-4">
                            อัพโหลดรายชื่อผู้รับบริการ
                        </span>
                    </a>
                </nav>
                <div class="buttons is-centered">
                    <a class="button is-danger" href="{{url_for('services.index', project_id=project_id)}}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/student_admin/organism_form.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    {% include "messages.html" %}
    <div class="columns">
      <div class="column">
        <table class="table is-striped">
          <thead>
          <th>Organism</th>
          <th></th>
          </thead>
          <tbody>
          {% for org in organisms %}
          <tr>
            <td>{{org.name}}</td>
            <td>
              <a href="{{url_for('student_admin.edit_organism', org_id=org.id, project_id=project_id)}}" class="button is-light">
                <span>edit</span>
              </a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <form method="post">
          {{form.hidden_tag()}}
          <div class="field">
            <label class="label">{{form.name.label}}</label>
            <div class="control">
              {{form.name(class="input")}}
            </div>
          </div>
          <div class="field">
            <input type="submit" {% if org_id %} value="Save" {% else %} value="Add" {% endif %}
                   class="button is-primary">
          </div>
        </form>
        <div class="buttons is-centered">
          <a class="button is-danger" href="{{url_for('student_admin.index', project_id=project_id)}}">
            Back
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/student_admin/upload_clients.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    {% include "messages.html" %}
    <div class="columns">
      <div class="column box is-two-thirds is-offset-2 has-text-centered">
        <form method="post" enctype="multipart/form-data">
          {{form.hidden_tag()}}
          <div class="field">
            <label class="label">{{form.upload.label}}</label>
            <div class="control">
              {{form.upload()}}
            </div>
          </div>
          <div class="field">
            <div class="control">
              <label class="checkbox">
                {{form.random_pid()}}
                {{form.random_pid.label}}
              </label>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <label class="checkbox">
                {{form.use_lab_number_as_client_number()}}
                {{form.use_lab_number_as_client_number.label}}
              </label>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <button type="submit" class="button is-primary">Upload</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/student_admin/users.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    {% include "messages.html" %}
    <div class="columns">
      <div class="column">
        <table class="table is-striped">
          <thead>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Email</th>
          <th></th>
          </thead>
          <tbody>
          {% for u in users %}
          <tr>
            <td>{{u.firstname}}</td>
            <td>{{u.lastname}}</td>
            <td>{{u.email}}</td>
            <td>
              <a href="{{url_for('student_admin.approve_user', user_id=u.id, project_id=project_id)}}" class="button is-light">
                <span>approve</span>
              </a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
        <div class="buttons is-centered">
          <a class="button is-danger" href="{{url_for('student_admin.index', project_id=project_id)}}">
            Back
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}