app/services/forms.py
from flask_wtf import FlaskForm
from wtforms import FormField, FieldList, BooleanField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired, Optional
from wtforms_alchemy import model_form_factory, QuerySelectField, QuerySelectMultipleField
from wtforms_components import SelectField

from app import db
from app.services.models import *

BaseModelForm = model_form_factory(FlaskForm)


class ModelForm(BaseModelForm):
    @classmethod
    def get_session(self):
        return db.session


def create_client_form(project_id):
    class ClientForm(ModelForm):
        class Meta:
            model = Client

        address = QuerySelectField('ที่อยู่',
                                   query_factory=lambda: ClientAddress.query.filter_by(project_id=project_id),
                                   get_label='name')
        use_pid_as_hn = BooleanField('ใช้หมายเลขบัตรปชช.เป็นรหัสผู้รับบริการ', default=False)

    return ClientForm


class ClientPhysicalProfileForm(ModelForm):
    class Meta:
        model = ClientPhysicalProfile


class TestForm(ModelForm):
    class Meta:
        model = Test


class TestRecordForm(ModelForm):
    class Meta:
        model = TestRecord

    results = SelectField('Results', validators=[Optional()])


def create_test_profile_record_form(profile):
    class TestProfileRecordForm(FlaskForm):
        for test in profile.tests:
            vars()[test.name] = FormField(TestRecordForm, default=TestRecord)
    return TestProfileRecordForm


class StoolTestReportItemForm(ModelForm):
    class Meta:
        model = StoolTestReportItem

    organism = QuerySelectField('Organism', query_factory=lambda: Organism.query.all(),
                                get_label='name')
    stage = QuerySelectField('Stage', query_factory=lambda: Stage.query.all(),
                             get_label='stage')


class StoolTestForm(ModelForm):
    class Meta:
        model = StoolTestRecord

    not_found = RadioField('Not found', choices=[(c, c) for c in ['Found', 'Not found']], default='Not found')

    items = FieldList(FormField(StoolTestReportItemForm,
                                default=StoolTestReportItem), min_entries=1)


class HealthRecordForm(ModelForm):
    class Meta:
        model = HealthRecord

    underlying_diseases = QuerySelectMultipleField('โรคประจำตัว',
                                                   query_factory=lambda: UnderlyingDisease.query.all(),
                                                   get_label='name',
                                                   allow_blank=True,
                                                   blank_text='กรุณาระบุโรค',
                                                   widget=widgets.ListWidget(prefix_label=False),
                                                   option_widget=widgets.CheckboxInput())
    family_diseases = QuerySelectMultipleField('โรคประจำตัวในครอบครัว',
                                               query_factory=lambda: FamilyDiseases.query.all(),
                                               get_label='name',
                                               allow_blank=True,
                                               blank_text='กรุณาระบุโรค',
                                               widget=widgets.ListWidget(prefix_label=False),
                                               option_widget=widgets.CheckboxInput())

app/services/__init__.py
from flask import Blueprint

service_bp = Blueprint('services', __name__, url_prefix='/services')


from . import views

app/services/views.py
import random
from collections import defaultdict
from datetime import datetime
from pytz import timezone

import arrow
import gviz_api
from flask import render_template, redirect, url_for, flash, request, make_response, jsonify
from flask_login import login_required, current_user
from sqlalchemy import or_

from app import db, superuser
from app.services import service_bp as services
from app.services.forms import create_client_form, ClientPhysicalProfileForm, TestForm, TestRecordForm, StoolTestForm, \
    HealthRecordForm, create_test_profile_record_form
from app.services.models import Client, ClientPhysicalProfile, Test, TestRecord, StoolTestRecord, HealthRecord, \
    Organism, Stage, StoolTestReportItem, Project, TestProfile


@services.route('/projects')
@login_required
def projects():
    projects = Project.query
    return render_template('services/projects.html', projects=projects)


@services.route('/projects/<int:project_id>')
@login_required
def index(project_id):
    return render_template('services/index.html', project_id=project_id)


@services.route('/projects/<int:project_id>/statistics')
@login_required
def show_statistics(project_id):
    return render_template('services/statistics.html', project_id=project_id)


@services.route('/projects/<int:project_id>/clients/registration', methods=['GET', 'POST'])
@login_required
def register_client(project_id):
    pid = request.args.get('pid')
    client = Client.query.filter_by(pid=pid).first()
    if client:
        flash('Existing client! Welcome back ;)', 'success')
        return redirect(url_for('services.edit_client', client_id=client.id))
    ClientForm = create_client_form(project_id)
    form = ClientForm()
    if form.validate_on_submit():
        client = Client()
        form.populate_obj(client)
        if form.use_pid_as_hn.data:
            client.client_number = client.pid
        client.project_id = project_id
        client.updated_by = current_user
        db.session.add(client)
        db.session.commit()
        flash('New client has been added.', 'success')
        return redirect(url_for('services.edit_client', client_id=client.id, project_id=project_id))
    else:
        for field in form.errors:
            flash(f'{field}: {form.errors[field]}', 'danger')
    return render_template('services/clients/registration.html', form=form, project_id=project_id)


@services.route('/projects/<int:project_id>/clients/<int:client_id>/edit', methods=['GET', 'POST', 'DELETE'])
@login_required
def edit_client(client_id, project_id):
    client = Client.query.get(client_id)
    health_form = None
    if client:
        if request.method == "DELETE":
            db.session.delete(client)
            db.session.commit()
            resp = make_response()
            resp.headers['HX-Redirect'] = url_for('services.list_clients', project_id=project_id)
            return resp

        ClientForm = create_client_form(project_id=client.project_id)
        form = ClientForm(obj=client)
        health_form = HealthRecordForm()
    else:
        flash('The client is not found.', 'danger')
    if form.validate_on_submit():
        form.populate_obj(client)
        client.updated_by = current_user
        db.session.add(client)
        db.session.commit()
        flash('Client data have been update.', 'success')
    return render_template('services/clients/registration.html',
                           project_id=project_id,
                           form=form, client=client, health_form=health_form)


@services.route('/random-pid')
@login_required
def random_pid():
    while True:
        pid = 'fake' + ''.join([str(random.randint(0, 9)) for i in range(9)])
        client = Client.query.filter_by(pid=pid).first()
        if client is None:
            break
    return f'''
      <input class="input" id="pid" name="pid" type="text" value="{pid}">
    '''


@services.route('/projects/<int:project_id>/clients')
@login_required
def list_clients(project_id):
    return render_template('services/clients/list.html', project_id=project_id)


@services.route('/api/projects/<int:project_id>/profiles/<int:profile_id>')
@login_required
def get_client_list_profile(project_id, profile_id):
    query = Client.query.filter_by(project_id=project_id)
    records_total = query.count()
    search = request.args.get('search[value]')
    query = query.filter(or_(Client.client_number.ilike('%{}%'.format(search)),
                             Client.firstname.ilike('%{}%'.format(search)),
                             Client.lastname.ilike('%{}%'.format(search)),
                             Client.pid.ilike('%{}%'.format(search)),
                             Client.address.has(name=search),
                             ),
                         )
    start = request.args.get('start', type=int)
    length = request.args.get('length', type=int)
    total_filtered = query.count()
    query = query.offset(start).limit(length)
    data = []
    for r in query:
        d = r.to_dict()
        if profile_id:
            d['url'] = url_for('services.add_test_profile_record',
                               client_id=r.id,
                               project_id=project_id,
                               profile_id=profile_id)
        elif request.args.get('for') == 'physical-exam':
            d['url'] = url_for('services.add_physical_exam_profile',
                               client_id=r.id,
                               project_id=project_id)
        elif request.args.get('for') == 'health-record':
            d['url'] = url_for('services.add_health_record',
                               client_id=r.id,
                               project_id=project_id)
        else:
            d['url'] = url_for('services.client_profile', client_id=r.id, project_id=project_id)
        data.append(d)
    return jsonify({'data': data,
                    'recordsFiltered': total_filtered,
                    'recordsTotal': records_total,
                    'draw': request.args.get('draw', type=int),
                    })


@services.route('/api/projects/<int:project_id>/clients')
@services.route('/api/projects/<int:project_id>/tests/<int:test_id>')
@login_required
def get_client_list(project_id, test_id=None):
    query = Client.query.filter_by(project_id=project_id)
    records_total = query.count()
    search = request.args.get('search[value]')
    query = query.filter(or_(Client.client_number.ilike('%{}%'.format(search)),
                             Client.firstname.ilike('%{}%'.format(search)),
                             Client.lastname.ilike('%{}%'.format(search)),
                             Client.pid.ilike('%{}%'.format(search)),
                             Client.address.has(name=search),
                             ),
                         )
    start = request.args.get('start', type=int)
    length = request.args.get('length', type=int)
    total_filtered = query.count()
    query = query.offset(start).limit(length)
    data = []
    for r in query:
        d = r.to_dict()
        if test_id:
            d['url'] = url_for('services.add_test_record',
                               client_id=r.id,
                               project_id=project_id,
                               test_id=test_id)
        elif request.args.get('for') == 'physical-exam':
            d['url'] = url_for('services.add_physical_exam_profile',
                               client_id=r.id,
                               project_id=project_id)
        elif request.args.get('for') == 'health-record':
            d['url'] = url_for('services.add_health_record',
                               client_id=r.id,
                               project_id=project_id)
        else:
            d['url'] = url_for('services.client_profile', client_id=r.id, project_id=project_id)
        data.append(d)
    return jsonify({'data': data,
                    'recordsFiltered': total_filtered,
                    'recordsTotal': records_total,
                    'draw': request.args.get('draw', type=int),
                    })


@services.route('/projects/<int:project_id>/clients/physical-exam')
@login_required
def physical_exam_profile_main(project_id):
    client_number = request.args.get('client_number')
    if client_number:
        client = Client.query.filter_by(client_number=client_number).first()
        if client:
            return redirect(url_for('services.add_physical_exam_profile', client_id=client.id, project_id=project_id))
    return render_template('services/clients/physical_exam_profile_main.html', project_id=project_id)


@services.route('/projects/<int:project_id>/clients/<int:client_id>/physical-exam', methods=['GET', 'POST'])
@login_required
def add_physical_exam_profile(client_id, project_id):
    client = Client.query.get(client_id)
    if not client:
        flash('Client not found', 'danger')
        return redirect(url_for('services.physical_exam_profile'))

    form = ClientPhysicalProfileForm()
    if form.validate_on_submit():
        pp = ClientPhysicalProfile()
        form.populate_obj(pp)
        pp.client = client
        pp.updated_by = current_user
        db.session.add(pp)
        db.session.commit()
        flash('New data have been saved.', 'success')
        return redirect(request.args.get('next') or url_for('services.physical_exam_profile_main', project_id=project_id))
    return render_template('services/clients/physical_exam_form.html', form=form, client=client, project_id=project_id)


@services.route('/projects/<int:project_id>/clients/physical-exam/<int:rec_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_physical_exam_profile(project_id, rec_id):
    rec = ClientPhysicalProfile.query.get(rec_id)
    form = ClientPhysicalProfileForm(obj=rec)
    if form.validate_on_submit():
        form.populate_obj(rec)
        rec.updated_by = current_user
        db.session.add(rec)
        db.session.commit()

app/templates/services/clients/health_record_main.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                <h1 class="title has-text-centered">Health Records</h1>
                <form method="get">
                    <div class="field">
                        <label class="label">ระบุรหัสผู้รับบริการ</label>
                        <div class="control">
                            <input class="input is-medium" name="client_number" placeholder="Client Number">
                        </div>
                    </div>
                    <div class="field">
                        <div class="buttons is-centered">
                            <a class="button is-light" href="{{url_for('services.index', project_id=project_id)}}">Back</a>
                            <input class="button is-primary" type="submit" value="Submit">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <table id="clientTable" class="table is-striped is-fullwidth">
                    <thead>
                    <th>Client Number</th>
                    <th>Name</th>
                    <th>Age</th>
                    <th>PID</th>
                    <th>Address</th>
                    <th></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
{{ super() }}
<script>
    $('document').ready(()=>{
        $('#clientTable').DataTable({
            ajax: {
                url: {{ url_for('services.get_client_list', project_id=project_id, for='health-record')|tojson|safe }},
    },
        columns: [
            { data: 'client_number' },
            {
                data: 'fullname',
            },
            { data: 'age' },
            { data: 'pid' },
            { data: 'address' },
            {
                data: 'url',
                render: function (data) {
                    return '<a class="has-text-info" href=' + data + '><span class="icon"><i class="fas fa-plus"></i></span><span>เพิ่มข้อมูล</span></a>'
                }
            }
        ],
            processing: true,
            serverSide: true,
    });
    })
</script>
{% endblock %}

app/templates/services/clients/list.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <nav class="breadcrumb" aria-label="breadcrumbs">
          <ul>
            <li><a href="{{url_for('services.index', project_id=project_id)}}">Home</a></li>
            <li class="is-active"><a href="#" aria-current="page">Clients</a></li>
          </ul>
        </nav>
        <h1 class="title has-text-centered">All Clients</h1>
        <div class="buttons is-centered">
          <a href="{{url_for('services.register_client', project_id=project_id)}}" class="button is-link">
            <span class="icon">
              <i class="fa-solid fa-user-plus"></i>
            </span>
            <span>Add Client</span>
          </a>
        </div>
        <table id="clientTable" class="table is-striped is-fullwidth">
          <thead>
          <th>Client Number</th>
          <th>Name</th>
          <th>Age</th>
          <th>PID</th>
          <th>Address</th>
          <th></th>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{% block scripts %}
{{ super() }}
<script>
  $('document').ready(()=>{
    $('#clientTable').DataTable({
      ajax: {
        url: {{ url_for('services.get_client_list', project_id=project_id)|tojson|safe }},
      },
      columns: [
        { data: 'client_number' },
        {
          data: 'fullname',
        },
        { data: 'age' },
        { data: 'pid' },
        { data: 'address' },
        {
          data: 'url',
          render: function (data) {
            return '<a href=' + data + '><span class="icon"><i class="fa-regular fa-eye"></i></span><span>profile</span></a>'
          }
        }
      ],
      processing: true,
      serverSide: true,
    });
  })
</script>
{% endblock %}

app/templates/services/clients/physical_exam_profile_main.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column">
                {% include "messages.html" %}
                <h1 class="title has-text-centered">Physical Examination</h1>
                <form method="get">
                    <div class="field">
                        <label class="label">ระบุรหัสผู้รับบริการ</label>
                        <div class="control">
                            <input class="input is-medium" name="client_number" placeholder="Client Number">
                        </div>
                    </div>
                    <div class="field">
                        <div class="buttons is-centered">
                            <a class="button is-light" href="{{url_for('services.index', project_id=project_id)}}">Back</a>
                            <input class="button is-primary" type="submit" value="Submit">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <table id="clientTable" class="table is-striped is-fullwidth">
                    <thead>
                    <th>Client Number</th>
                    <th>Name</th>
                    <th>Age</th>
                    <th>PID</th>
                    <th>Address</th>
                    <th></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
{{ super() }}
<script>
    $('document').ready(()=>{
        $('#clientTable').DataTable({
            ajax: {
                url: {{ url_for('services.get_client_list', project_id=project_id, for='physical-exam')|tojson|safe }},
    },
        columns: [
            { data: 'client_number' },
            {
                data: 'fullname',
            },
            { data: 'age' },
            { data: 'pid' },
            { data: 'address' },
            {
                data: 'url',
                render: function (data) {
                    return '<a class="has-text-info" href=' + data + '><span class="icon"><i class="fas fa-plus"></i></span><span>เพิ่มข้อมูล</span></a>'
                }
            }
        ],
            processing: true,
            serverSide: true,
    });
    })
</script>
{% endblock %}

app/templates/services/clients/registration.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="{{url_for('services.index', project_id=project_id)}}">Home</a></li>
        <li><a href="{{url_for('services.list_clients', project_id=project_id)}}">Clients</a></li>
        <li class="is-active"><a href="#" aria-current="page">Client Edit</a></li>
      </ul>
    </nav>
    {% include "messages.html" %}
    <div class="columns">
      <div class="column is-two-thirds is-offset-2">
        <h1 class="title has-text-centered">Client Registration/Edit</h1>
        {% if not client %}
        <form method="get">
          <div class="field">
            <div class="control">
              <input name="pid" class="input is-medium" placeholder="Personal Identification Number">
            </div>
          </div>
          <div class="field">
            <div class="buttons is-centered">
              <input type="submit" value="Search" class="button is-primary">
            </div>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
    <div class="columns">
      <div class="column {% if not client %}is-two-thirds is-offset-2{% endif %}">
        <form method="post">
          <div class="box">
          {{ form.hidden_tag() }}
          <div class="field">
            <label class="label">{{form.firstname.label}}</label>
            <div class="control">
              {{ form.firstname(class="input") }}
            </div>
          </div>
          <div class="field">
            <label class="label">{{form.lastname.label}}</label>
            <div class="control">
              {{ form.lastname(class="input") }}
            </div>
          </div>
            <div class="field">
              <label class="label">{{form.gender.label}}</label>
              <div class="control">
                {{ form.gender() }}
              </div>
            </div>
          <div class="field">
            <label class="label">คำนวณปีค.ศ.จากพ.ศ.</label>
            <div class="control" x-data="{year: new Date().getFullYear() + 543}">
              <input name="buddhistYear"
                     x-model="year"
                     x-on:keyUp="setCalendarDate(year - 543)"
                     placeholder="คำนวณปีค.ศ.จากพ.ศ." class="input">
            </div>
          </div>
          <div class="field">
            <label class="label">{{form.dob.label}}</label>
            <div class="control">
              {{ form.dob(class="input", type="text") }}
            </div>
          </div>
            <div class="field">
              <label class="label">{{form.age_.label}}</label>
              <div class="control">
                {{ form.age_(class="input") }}
              </div>
            </div>
          <div class="field">
            <label class="label">{{form.pid.label}}</label>
            <div class="control">
              {{ form.pid(class="input") }}
              <p class="help is-info">หากไม่ทราบหมายเลขบัตรประชาชนให้กดปุ่ม generate random PID</p>
            </div>
            <button class="button is-link is-rounded"
                    hx-swap="outerHTML"
                    hx-target="#pid"
                    hx-get="{{ url_for('services.random_pid') }}">
              <span class="icon">
                <i class="fa-solid fa-shuffle"></i>
              </span>
              <span>
                Generate Random PID
              </span>
            </button>
          </div>
          <div class="field">
            <div class="select">
              {{form.address()}}
            </div>
          </div>
          {% if not client %}
          <div class="field">
            <label class="checkbox">
              {{ form.use_pid_as_hn() }}
              {{ form.use_pid_as_hn.label }}
            </label>
          </div>
          {% endif %}
          <div class="field">
            <label class="label">{{form.client_number.label}}</label>
            <div class="control">
              {{ form.client_number(class="input") }}
            </div>
          </div>
          </div>
          <div class="field is-grouped is-grouped-centered">
            <div class="control">
              <a class="button is-light" href="{{ url_for('services.index', project_id=project_id) }}">Back</a>
            </div>
            <div class="control">
              <input class="button is-primary" type="submit" value="Submit">
            </div>
          </div>
        </form>
      </div>
      {% if client %}
      <div class="column">
        <div class="box">
          <h1 class="title">Register Stool Examination</h1>
          <form method="get" action="{{url_for('services.stool_exam_main',project_id=project_id, client_id=client.id)}}">
            <input type="hidden" name="next" value="{{url_for('services.register_client', project_id=project_id)}}">
            <div class="field">
              <input class="input" name="lab_number">
            </div>
            <div class="field">
              <label class="label">Collected At</label>
              <div class="control">
                                <input type="text" class="input" id="collectionDatetime" name="collection_datetime">
                                </div>
            </div>
            <div class="field">
              <input type="submit" value="Register" class="button is-warning">
            </div>
          </form>
        </div>
        <div class="box">
          <label class="label">
            Stool Exam History
          </label>
          <table class="table is-striped is-bordered">
            <th>Lab Number</th>
            <th>Received At</th>
            <th>Collected At</th>
            {% for rec in client.stool_exam_records %}
            <tr>
              <td>{{rec.lab_number}}</td>
              <td>{{rec.updated_at|localdatetime}}</td>
              <td>{{rec.collection_datetime.strftime('%d/%m/%Y %H:%M:%S') }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
      {% endif %}
    </div>
    {% if client and client.health_records.count() == 0 %}
    <div class="columns">
      <div class="column">
          <h1 class="title has-text-centered">Health Record Form</h1>
          <div class="box">
            <form method="post" action="{{url_for('services.add_health_record',project_id=project_id, client_id=client.id, next=request.url)}}">
              {{health_form.hidden_tag()}}
              <div class="field">
                <label class="label">{{health_form.fasting_time.label}}</label>
                <div class="control">
                  {{health_form.fasting_time(class="input")}}
                </div>
              </div>
              <div class="field">
                <label class="label">{{health_form.underlying_diseases.label}}</label>
                <div class="control">
                  {{health_form.underlying_diseases()}}
                </div>
              </div>
              <div class="field">
                <label class="label">{{health_form.other_underlying_disease.label}}</label>
                <div class="control">
                  {{health_form.other_underlying_disease(class="input")}}
                </div>
              </div>
              <div class="field">
                <label class="label">{{health_form.family_diseases.label}}</label>
                <div class="control">
                  {{health_form.family_diseases()}}
                </div>
              </div>
              <div class="field">
                <label class="label">{{health_form.other_family_disease.label}}</label>
                <div class="control">
                  {{health_form.other_family_disease(class="input")}}
                </div>
              </div>
              <div class="field">
                <label class="label">{{health_form.suggestion.label}}</label>
                <div class="control">
                  {{health_form.suggestion(class="textarea")}}
                </div>
              </div>
              <div class="field is-grouped is-grouped-centered">
                <a href="{{url_for('services.health_record_main', project_id=project_id)}}" class="button is-light">Back</a>
                <input type="submit" value="Submit" class="button is-primary">
              </div>
            </form>
          </div>
      </div>
    </div>
    {% elif client and client.health_records.count() > 0 %}
    <div class="box">
      <label class="label">ประวัติสุขภาพ</label>
      <table class="table is-striped">
        <thead>
        <th>ID</th>
        <th>Updated At</th>
        <th>By</th>
        <th></th>
        </thead>
        {% for rec in client.health_records %}
        <tr>
          <td>{{rec.id}}</td>
          <td>{{rec.updated_at|localdatetime}}</td>
          <td>{{rec.updated_by.firstname}}</td>
          <td>
            <a class="button is-light" href="{{url_for('services.add_health_record', project_id=project_id, record_id=rec.id, client_id=client.id, next=request.url)}}">
                <span class="icon">
                  <i class="fa-solid fa-pencil"></i>
                </span>
              <span>edit</span>
            </a>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
    {% endif %}
  </div>
</section>
{% endblock %}
{% block scripts %}
{{super()}}
<script src="//unpkg.com/alpinejs" defer></script>
<script>
  $('#dob').daterangepicker({
    singleDatePicker: true,
    showDropdowns: true,
    autoUpdateInput: true,
    locale: {
      format: 'YYYY-MM-DD'
    }
  });
</script>
<script>
  $('#collectionDatetime').daterangepicker({
    singleDatePicker: true,
    timePicker: true,
    showDropdowns: true,
    timePickerIncrement: 15,
    timePicker24Hour: true,
    autoUpdateInput: true,
    locale: {
      format: 'YYYY-MM-DD HH:mm:ss'
    }
  });
  let setCalendarDate = function (year) {
    if (year > 1960) {
      $('#dob').data('daterangepicker').setStartDate(year + '-01-01')
      $('#dob').data('daterangepicker').setEndDate(year + '-01-01')
    }
  }
</script>
{% endblock %}