app/services/forms.py
from flask_wtf import FlaskForm
from wtforms import FormField, FieldList, BooleanField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired, Optional
from wtforms_alchemy import model_form_factory, QuerySelectField, QuerySelectMultipleField
from wtforms_components import SelectField

from app import db
from app.services.models import *

BaseModelForm = model_form_factory(FlaskForm)


class ModelForm(BaseModelForm):
    @classmethod
    def get_session(self):
        return db.session


def create_client_form(project_id):
    class ClientForm(ModelForm):
        class Meta:
            model = Client

        address = QuerySelectField('ที่อยู่',
                                   query_factory=lambda: ClientAddress.query.filter_by(project_id=project_id),
                                   get_label='name')
        use_pid_as_hn = BooleanField('ใช้หมายเลขบัตรปชช.เป็นรหัสผู้รับบริการ', default=False)

    return ClientForm


class ClientPhysicalProfileForm(ModelForm):
    class Meta:
        model = ClientPhysicalProfile


class TestForm(ModelForm):
    class Meta:
        model = Test


class TestRecordForm(ModelForm):
    class Meta:
        model = TestRecord

    results = SelectField('Results', validators=[Optional()])


def create_test_profile_record_form(profile):
    class TestProfileRecordForm(FlaskForm):
        for test in profile.tests:
            vars()[test.name] = FormField(TestRecordForm, default=TestRecord)
    return TestProfileRecordForm


class StoolTestReportItemForm(ModelForm):
    class Meta:
        model = StoolTestReportItem

    organism = QuerySelectField('Organism', query_factory=lambda: Organism.query.all(),
                                get_label='name')
    stage = QuerySelectField('Stage', query_factory=lambda: Stage.query.all(),
                             get_label='stage')


class StoolTestForm(ModelForm):
    class Meta:
        model = StoolTestRecord

    not_found = RadioField('Not found', choices=[(c, c) for c in ['Found', 'Not found']], default='Not found')

    items = FieldList(FormField(StoolTestReportItemForm,
                                default=StoolTestReportItem), min_entries=1)


class HealthRecordForm(ModelForm):
    class Meta:
        model = HealthRecord

    underlying_diseases = QuerySelectMultipleField('โรคประจำตัว',
                                                   query_factory=lambda: UnderlyingDisease.query.all(),
                                                   get_label='name',
                                                   allow_blank=True,
                                                   blank_text='กรุณาระบุโรค',
                                                   widget=widgets.ListWidget(prefix_label=False),
                                                   option_widget=widgets.CheckboxInput())
    family_diseases = QuerySelectMultipleField('โรคประจำตัวในครอบครัว',
                                               query_factory=lambda: FamilyDiseases.query.all(),
                                               get_label='name',
                                               allow_blank=True,
                                               blank_text='กรุณาระบุโรค',
                                               widget=widgets.ListWidget(prefix_label=False),
                                               option_widget=widgets.CheckboxInput())

app/services/__init__.py
from flask import Blueprint

service_bp = Blueprint('services', __name__, url_prefix='/services')


from . import views

app/services/views.py
import random
from collections import defaultdict
from datetime import datetime
from pytz import timezone

import arrow
import gviz_api
from flask import render_template, redirect, url_for, flash, request, make_response, jsonify
from flask_login import login_required, current_user
from sqlalchemy import or_

from app import db, superuser
from app.services import service_bp as services
from app.services.forms import create_client_form, ClientPhysicalProfileForm, TestForm, TestRecordForm, StoolTestForm, \
    HealthRecordForm, create_test_profile_record_form
from app.services.models import Client, ClientPhysicalProfile, Test, TestRecord, StoolTestRecord, HealthRecord, \
    Organism, Stage, StoolTestReportItem, Project, TestProfile


@services.route('/projects')
@login_required
def projects():
    projects = Project.query
    return render_template('services/projects.html', projects=projects)


@services.route('/projects/<int:project_id>')
@login_required
def index(project_id):
    return render_template('services/index.html', project_id=project_id)


@services.route('/projects/<int:project_id>/statistics')
@login_required
def show_statistics(project_id):
    return render_template('services/statistics.html', project_id=project_id)


@services.route('/projects/<int:project_id>/clients/registration', methods=['GET', 'POST'])
@login_required
def register_client(project_id):
    pid = request.args.get('pid')
    client = Client.query.filter_by(pid=pid).first()
    if client:
        flash('Existing client! Welcome back ;)', 'success')
        return redirect(url_for('services.edit_client', client_id=client.id))
    ClientForm = create_client_form(project_id)
    form = ClientForm()
    if form.validate_on_submit():
        client = Client()
        form.populate_obj(client)
        if form.use_pid_as_hn.data:
            client.client_number = client.pid
        client.project_id = project_id
        client.updated_by = current_user
        db.session.add(client)
        db.session.commit()
        flash('New client has been added.', 'success')
        return redirect(url_for('services.edit_client', client_id=client.id, project_id=project_id))
    else:
        for field in form.errors:
            flash(f'{field}: {form.errors[field]}', 'danger')
    return render_template('services/clients/registration.html', form=form, project_id=project_id)


@services.route('/projects/<int:project_id>/clients/<int:client_id>/edit', methods=['GET', 'POST', 'DELETE'])
@login_required
def edit_client(client_id, project_id):
    client = Client.query.get(client_id)
    health_form = None
    if client:
        if request.method == "DELETE":
            db.session.delete(client)
            db.session.commit()
            resp = make_response()
            resp.headers['HX-Redirect'] = url_for('services.list_clients', project_id=project_id)
            return resp

        ClientForm = create_client_form(project_id=client.project_id)
        form = ClientForm(obj=client)
        health_form = HealthRecordForm()
    else:
        flash('The client is not found.', 'danger')
    if form.validate_on_submit():
        form.populate_obj(client)
        client.updated_by = current_user
        db.session.add(client)
        db.session.commit()
        flash('Client data have been update.', 'success')
    return render_template('services/clients/registration.html',
                           project_id=project_id,
                           form=form, client=client, health_form=health_form)


@services.route('/random-pid')
@login_required
def random_pid():
    while True:
        pid = 'fake' + ''.join([str(random.randint(0, 9)) for i in range(9)])
        client = Client.query.filter_by(pid=pid).first()
        if client is None:
            break
    return f'''
      <input class="input" id="pid" name="pid" type="text" value="{pid}">
    '''


@services.route('/projects/<int:project_id>/clients')
@login_required
def list_clients(project_id):
    return render_template('services/clients/list.html', project_id=project_id)


@services.route('/api/projects/<int:project_id>/profiles/<int:profile_id>')
@login_required
def get_client_list_profile(project_id, profile_id):
    query = Client.query.filter_by(project_id=project_id)
    records_total = query.count()
    search = request.args.get('search[value]')
    query = query.filter(or_(Client.client_number.ilike('%{}%'.format(search)),
                             Client.firstname.ilike('%{}%'.format(search)),
                             Client.lastname.ilike('%{}%'.format(search)),
                             Client.pid.ilike('%{}%'.format(search)),
                             Client.address.has(name=search),
                             ),
                         )
    start = request.args.get('start', type=int)
    length = request.args.get('length', type=int)
    total_filtered = query.count()
    query = query.offset(start).limit(length)
    data = []
    for r in query:
        d = r.to_dict()
        if profile_id:
            d['url'] = url_for('services.add_test_profile_record',
                               client_id=r.id,
                               project_id=project_id,
                               profile_id=profile_id)
        elif request.args.get('for') == 'physical-exam':
            d['url'] = url_for('services.add_physical_exam_profile',
                               client_id=r.id,
                               project_id=project_id)
        elif request.args.get('for') == 'health-record':
            d['url'] = url_for('services.add_health_record',
                               client_id=r.id,
                               project_id=project_id)
        else:
            d['url'] = url_for('services.client_profile', client_id=r.id, project_id=project_id)
        data.append(d)
    return jsonify({'data': data,
                    'recordsFiltered': total_filtered,
                    'recordsTotal': records_total,
                    'draw': request.args.get('draw', type=int),
                    })


@services.route('/api/projects/<int:project_id>/clients')
@services.route('/api/projects/<int:project_id>/tests/<int:test_id>')
@login_required
def get_client_list(project_id, test_id=None):
    query = Client.query.filter_by(project_id=project_id)
    records_total = query.count()
    search = request.args.get('search[value]')
    query = query.filter(or_(Client.client_number.ilike('%{}%'.format(search)),
                             Client.firstname.ilike('%{}%'.format(search)),
                             Client.lastname.ilike('%{}%'.format(search)),
                             Client.pid.ilike('%{}%'.format(search)),
                             Client.address.has(name=search),
                             ),
                         )
    start = request.args.get('start', type=int)
    length = request.args.get('length', type=int)
    total_filtered = query.count()
    query = query.offset(start).limit(length)
    data = []
    for r in query:
        d = r.to_dict()
        if test_id:
            d['url'] = url_for('services.add_test_record',
                               client_id=r.id,
                               project_id=project_id,
                               test_id=test_id)
        elif request.args.get('for') == 'physical-exam':
            d['url'] = url_for('services.add_physical_exam_profile',
                               client_id=r.id,
                               project_id=project_id)
        elif request.args.get('for') == 'health-record':
            d['url'] = url_for('services.add_health_record',
                               client_id=r.id,
                               project_id=project_id)
        else:
            d['url'] = url_for('services.client_profile', client_id=r.id, project_id=project_id)
        data.append(d)
    return jsonify({'data': data,
                    'recordsFiltered': total_filtered,
                    'recordsTotal': records_total,
                    'draw': request.args.get('draw', type=int),
                    })


@services.route('/projects/<int:project_id>/clients/physical-exam')
@login_required
def physical_exam_profile_main(project_id):
    client_number = request.args.get('client_number')
    if client_number:
        client = Client.query.filter_by(client_number=client_number).first()
        if client:
            return redirect(url_for('services.add_physical_exam_profile', client_id=client.id, project_id=project_id))
    return render_template('services/clients/physical_exam_profile_main.html', project_id=project_id)


@services.route('/projects/<int:project_id>/clients/<int:client_id>/physical-exam', methods=['GET', 'POST'])
@login_required
def add_physical_exam_profile(client_id, project_id):
    client = Client.query.get(client_id)
    if not client:
        flash('Client not found', 'danger')
        return redirect(url_for('services.physical_exam_profile'))

    form = ClientPhysicalProfileForm()
    if form.validate_on_submit():
        pp = ClientPhysicalProfile()
        form.populate_obj(pp)
        pp.client = client
        pp.updated_by = current_user
        db.session.add(pp)
        db.session.commit()
        flash('New data have been saved.', 'success')
        return redirect(request.args.get('next') or url_for('services.physical_exam_profile_main', project_id=project_id))
    return render_template('services/clients/physical_exam_form.html', form=form, client=client, project_id=project_id)


@services.route('/projects/<int:project_id>/clients/physical-exam/<int:rec_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_physical_exam_profile(project_id, rec_id):
    rec = ClientPhysicalProfile.query.get(rec_id)
    form = ClientPhysicalProfileForm(obj=rec)
    if form.validate_on_submit():
        form.populate_obj(rec)
        rec.updated_by = current_user
        db.session.add(rec)
        db.session.commit()

app/templates/services/index.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    {% include "messages.html" %}
    <div class="columns">
      <div class="column is-two-thirds is-offset-2 has-text-centered">
        <nav class="panel is-primary">
          <p class="panel-heading">
            Menu
          </p>
          <a class="panel-block is-active" href="{{url_for('services.register_client', project_id=project_id)}}">
            <span class="panel-icon">
              <i class="fa-solid fa-chevron-right"></i>
            </span>
            <span class="is-size-4">
              Client Registration
            </span>
          </a>
          <a class="panel-block is-active" href="{{url_for('services.list_clients', project_id=project_id)}}">
            <span class="panel-icon">
              <i class="fa-solid fa-chevron-right"></i>
            </span>
            <span class="is-size-4">
              Client List
            </span>
          </a>
          <a class="panel-block is-active" href="{{url_for('services.physical_exam_profile_main', project_id=project_id)}}">
            <span class="panel-icon">
              <i class="fa-solid fa-chevron-right"></i>
            </span>
            <span class="is-size-4">
              Physical Examination
            </span>
          </a>
          <a class="panel-block is-active" href="{{url_for('services.health_record_main', project_id=project_id)}}">
            <span class="panel-icon">
              <i class="fa-solid fa-chevron-right"></i>
            </span>
            <span class="is-size-4">
              Health Records
            </span>
          </a>
          <a class="panel-block is-active" href="{{url_for('services.stool_exam_main', project_id=project_id)}}">
            <span class="panel-icon">
              <i class="fa-solid fa-chevron-right"></i>
            </span>
            <span class="is-size-4">
              Stool Examination
            </span>
          </a>
          <a class="panel-block is-active" href="{{url_for('services.list_tests', project_id=project_id)}}">
            <span class="panel-icon">
              <i class="fa-solid fa-chevron-right"></i>
            </span>
            <span class="is-size-4">
              Tests
            </span>
          </a>
          <a class="panel-block is-active" href="{{url_for('services.show_statistics', project_id=project_id)}}">
            <span class="panel-icon">
              <i class="fa-solid fa-chevron-right"></i>
            </span>
            <span class="is-size-4">
              Statistics
            </span>
          </a>
        </nav>
        <div class="buttons is-centered">
          <a class="button is-warning" href="{{url_for('student_admin.index', project_id=project_id)}}">
            <span class="icon">
             <i class="fa-solid fa-gear"></i>
            </span>
            <span>Admin</span>
          </a>
          <a class="button is-danger" href="{{url_for('auth.logout')}}">
            Log Out
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/services/projects.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        {% include "messages.html" %}
        <div class="columns">
            <div class="column is-two-thirds is-offset-2 has-text-centered">
                <nav class="panel is-primary">
                    <p class="panel-heading">
                        Project
                    </p>
                    {% for project in projects %}
                    <a class="panel-block is-active" href="{{url_for('services.index', project_id=project.id)}}">
                        <span class="panel-icon">
                          <i class="fa-solid fa-chevron-right"></i>
                        </span>
                        <span class="is-size-4">
                            {{ project.name }}
                        </span>
                    </a>
                    {% endfor %}
                </nav>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/services/statistics.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="columns">
        <div class="column">
            <h1 class="title has-text-centered">Statistics</h1>
        </div>
    </div>
    <div class="columns">
        <div class="column">
            <div id="piechart" style="width: 900px; height: 500px;"></div>
        </div>
    </div>
    <div class="columns">
        <div class="column">
            <div id="piechart2" style="width: 900px; height: 500px;"></div>
        </div>
    </div>
    <div class="columns">
        <div class="column">
            <div id="piechart3" style="width: 900px; height: 500px;"></div>
        </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
{{super()}}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

        let jsonData = $.ajax({
            url: "{{url_for('services.get_stool_exam_statistics', project_id=project_id)}}",
            dataType: "json",
            async: false
        }).responseText;

        let data = new google.visualization.DataTable(jsonData);

        let options = {
            title: 'Stool Exam Summary'
        };

        let chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
    }
</script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

        let jsonData = $.ajax({
            url: "{{url_for('services.get_stool_exam_statistics_address', project_id=project_id)}}",
            dataType: "json",
            async: false
        }).responseText;

        let data = new google.visualization.DataTable(jsonData);

        let options = {
            title: 'Stool Exam Specimens Collected'
        };

        let chart2 = new google.visualization.ColumnChart(document.getElementById('piechart2'));

        chart2.draw(data, options);
    }
</script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

        let jsonData = $.ajax({
            url: "{{url_for('services.get_stool_exam_statistics_processed', project_id=project_id)}}",
            dataType: "json",
            async: false
        }).responseText;

        let data = new google.visualization.DataTable(jsonData);

        let options = {
            title: 'Stool Exam Specimens Processed'
        };

        let chart3 = new google.visualization.PieChart(document.getElementById('piechart3'));

        chart3.draw(data, options);
    }
</script>
{% endblock %}